channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip

  - pytorch
  - pytorch-lightning
  - torchvision
  - wandb

  - pandas
  - scikit-learn
  - rich
  - typer
  - loguru

  - black
  - isort
  - flake8
  - flake8-bugbear
  - mypy
  - ipywidgets
  - pre-commit

  - pip:
      - timm
